channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.19.1
  - pip=19.3.1
  - notebook>=6.1,<6.2
  - jupyterlab>=2.2,<3
  - sidecar=0.4.0
  - ipywidgets=7.5.1
  - pythreejs>=2.2,<2.3
  - cadquery=2.0.0
  - pip:
    - jupyter_cadquery==1.0.0
